[package]
name = "lox_lib"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lexer_benchmarks"
harness = false

[dependencies]
anyhow = "1.0.47"
clap = "2.33.3"
lazy_static = "1.4.0"